

import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {

  @override
  Map<String , Map<String, String>> get keys => {
    'en_US' : {
      'email_hint' : 'User Name' ,
      'enter_email_hint' : 'Enter email/user' ,
      'type_email_here' : 'Type email/user here',
      'pass_hint' : 'Password' ,
      'enter_pass_hint' : 'Enter password' ,
      'type_pass_here' : 'Type password here',

      'internet_exception' : "We're unable tp show results.\nPlease check your data\nconenction." ,
      'general_exception' : "We're unable to process your request.\n Please try again" ,
      'welcome_back' : 'Welcome\nBack' ,
      'login' :'Login' ,
      'next' :'Next' ,
      'password_hint' :'Password' ,
      'student_uid' :'Student UID' ,

      'all_users': 'All Users',
      'admin': 'Admin',
      'manager': 'Managers',
      'counselors':'Counselors',
      'agent': "Agents",
      'admission': 'Admission',
      'filling' : 'Filling',
      'reception' : 'Reception',
      'leads': 'Leads',
      'all_leads' : 'All Leads',
      'all_client' : 'All Clients',
      'add_leads': 'Add Leads',
      'assign_leads': 'Assign Leads',
      'via_lb_leads' : 'Via LB Leads',
      're_alloc_req': 'Re-allocation Requests',
      'lead_alloc_req':'Lead Allocation Request',
      'bulk_leads-delete' : 'Bulk Leads Delete',
      'auto_dial_lead' : 'Auto Dial Lead',
      'masters': 'Masters',
      'followups': 'Followups',
      'today_followups' : 'Today Followups',
      'allocated_leads' : 'Allocated Leads',
      'filling_process' : 'Filling Process',
      'pending_followups':'Pending Followups',
      'today_done_followups':'Today\'s Done Followups',
      'assign_admissions':'Assign Admissions',        
      'assign_filling' : 'Assign Filling',
      'payment_status': 'Payment Status',
      'expected_walkin': 'Expected Walkin',
      'expected_sale': 'Expected Sale',
      'counseling_feedbacks' :'Counseling Feedbacks',
      'sop':'SOP',
      'buy_SOP': 'Buy SOP',
      'financial':'Financial',
      'expenses': 'Expenses',
      'cash_transfer': 'Cash Deposit/Transfer',
      'cash_flow_rep':'Cash Flow Report',
      'all_reports' : 'All Reports',
      'overall_performense':'Overall Performense',
      'camp_status_report':'Campaign Status Report',
      'branch_admi_clg': 'Branch/Colleges Admissions',
      'add_dropout' : 'Add Dropout',
      'Tips_msg':'Tips & Messages',
      'country_process':'Country Process',
      'canada' :'Canada',
      'nwz':'NWZ',
      'aus': 'AUS',
      'sample_documents':'Sample Documents',
      'support': 'Support',
      'gic_guide' : 'GIC Guide',
      'appointments' : 'Appointments',
      'fintech_services':'Fintech Services',
      'rfs':'Request Fintech Services',
      'afs':'Applied Fintech Services',
      'sop_generator':'AI SOP Generator',
      'course_finder': 'Course Finder',
      'upload_institute_course': 'Upload Institute & Courses',
      'inbox_configuration': 'Inbox Configuration',
      'sms_template': 'SMS Template',
      'config_smtp': 'Config SMTP',
      'email_templates': 'Email Templates',
      'whatsapp_temp': 'Whatsapp Templates',
      'campaigns': 'Campaigns',
      'clg_agent':'College Agent',
      'country':'Country',
      'intake' :'Intake',
      'city' : 'City',
      'campuses': 'Campuses',
      'qualification' :'Qualification',
      'stream':'Stream',
      'institute':'Institute',
      'course':'Course',
      'branch': 'Branch',
      'status' : 'Status',
      'sub_status':'Sub Status',
      'source':'Source',
      'admision_doc_check':'Admision Docs Checklist',
      'filing_doc_check':'filing Docs Checklist',
      'registration_plans':'Registration Plans',
      'expense_types':'Expense Types',
      'bank_details':'Bank Details',
      'ip_add_access':'IP Address Access',
      'access_grant':'Access Grant',
      'setting':'Setting',
      'apply_leaves' :'Apply Leaves',
      'guides' :'Guides',
      'help':'Help',
      'new_dmission':'New Admission',
      'all_admission':'All Admission',
      'refund_process':'Refund Process',
      'close_course_clg':'Closed Courses/Colleges',
      'reports':'Reports',
      'console_report':'Console Report',
      'count_report':'Count Report',
      'filing_docs_check':'Filing Docs Checklist',
      'payment_approval':'Payment Approval',
      'admissions':'Admissions',
      'earning_reports':'Earning Reports',
      'visa_counselor':'Visa Counselor',
      'left_counselor':'Left Counselor',
      'visa_branches':'Visa Branches',
      'left_branches':'Left Branches',
      'gic_request' : 'GIC Request',
      'walking':'Walking',
      'call' : 'Call',
      'offer_latter': 'Offer Latter',
      'applied':'APPLIED',
      'notapplied':'NOT APPLIED',
      'recived':'RECIVED',
      'notrecived':'NOT RECIVED',
      'reg_collection':'Collection',
      'coll_by_reg':'Collection By Reg',
      'registration': 'REGISTRATION',
      'package': 'PACKAGE',
      'due':'DUE',
      'gic':'GIC',
      'open':'OPENED',
      'pending' : 'PENDING',
      'visa' : 'Visa',
      'aproved' :'APROVED',
      'refused' : 'REFUSED',
      'files' :'Files',
      'lodge':'LODGE',
      'notlodge':'NOT LODGE',
      'ttfee': 'TT Fee',
      'paid':'PAID',
      'notpaid' : 'NOT PAID',
      'institute_fee' : 'Institute Fee',
      'earning':'Earning',
      'target':'TARGET',
      'achived' : 'ACHIEVE',
      'email': 'Email',
      'phone':'Phone',
      'fName': 'First Name',
      'lName': 'Last Name',
      'errorFname' : 'Please enter first name',
      'errorLname' : 'Please enter last name',
      'errorEmail' : 'Please enter email',
      'errorPhone' : 'Please enter phone',
      'errorPassword' : 'Please enter password',
      'validEmail' : 'Please enter a valid email address',
      'validMobile' : 'Please enter a valid mobile',
      'invalidChar' : 'Invalid characters',
      'userName' : 'Username',
      'errorUsername' : 'Please enter User Name',
      'did' : 'DID',
      'errorDid' : 'Please enter DID',
      'dialerIp' : 'Dialer IP',
      'errorDialerIp' : 'Please enter Dialer IP',
      'campaignId' : 'Campaign Id',
      'errorCampaignId' : 'Please enter Campaign Id',

    },
    'hi_IN' : {
      'Email/User': 'ईमेल/उपयोगकर्ता',
      'email_hint': 'ईमेल/उपयोगकर्ता',
      'enter_email_hint': 'ईमेल/उपयोगकर्ता दर्ज करें',
      'type_email_here': 'यहाँ ईमेल/उपयोगकर्ता टाइप करें',
      'pass_hint': 'पासवर्ड',
      'enter_pass_hint': 'पासवर्ड दर्ज करें',
      'type_pass_here': 'यहाँ पासवर्ड टाइप करें',
      'internet_exception': 'हम परिणाम दिखाने में असमर्थ हैं।\nकृपया अपनी डेटा कनेक्शन की जाँच करें।',
      'general_exception': 'हम आपके अनुरोध को प्रोसेस करने में असमर्थ हैं।\nकृपया पुनः प्रयास करें।',
      'welcome_back': 'वेलकम\nबैक',
      'login': 'लॉगिन',
      'next': 'अगला',
      'password_hint': 'पासवर्ड',
      'company_name': 'कंपनी का नाम',
      'all_users': 'सभी उपयोगकर्ता',
      'admin': 'व्यवस्थापक',
      'manager': 'प्रबंधक',
      'counselors': 'परामर्शदाता',
      'agent': 'प्रतिनिधि',
      'admission': 'प्रवेश',
      'filling': 'भरना',
      'reception': 'स्वागत',
      'leads': 'नेतृत्व',
      'all_leads': 'सभी नेतृत्व',
      'all_client': 'सभी ग्राहक',
      'add_leads': 'नेतृत्व जोड़ें',
      'assign_leads': 'नेतृत्व का निरुपण करें',
      'via_lb_leads': 'LB नेतृत्व के माध्यम से',
      're_alloc_req': 'पुनः आवंटन अनुरोध',
      'lead_alloc_req': 'नेतृत्व आवंटन अनुरोध',
      'bulk_leads-delete': 'बल्क नेतृत्व हटाएं',
      'auto_dial_lead': 'स्वचालित डायल नेतृत्व',
      'masters': 'मास्टर्स',
      'followups': 'अनुवर्ती',
      'today_followups': 'आज के अनुवर्ती',
      'pending_followups': 'बकाया अनुवर्ती',
      'today_done_followups': 'आज के पूरे अनुवर्ती',
      'assign_admissions': 'प्रवेश का निरुपण करें',
      'assign_filling': 'भरना निरुपण करें',
      'payment_status': 'भुगतान स्थिति',
      'expected_walkin': 'प्रत्याशित वॉकिन',
      'expected_sale': 'प्रत्याशित बिक्री',
      'sop': 'SOP',
      'buy_SOP': 'SOP खरीदें',
      'financial': 'वित्तीय',
      'expenses': 'व्यय',
      'cash_transfer': 'नकद जमा/स्थानांतरण',
      'cash_flow_rep': 'नकद निर्धारण रिपोर्ट',
      'all_reports': 'सभी रिपोर्टें',
      'overall_performense': 'समग्र प्रदर्शन',
      'camp_status_report': 'कैंपेन स्थिति रिपोर्ट',
      'branch_admi_clg': 'शाखा/कॉलेज प्रवेश',
      'add_dropout': 'निकासी जोड़ें',
      'Tips_msg': 'सुझाव और संदेश',
      'country_process': 'देश प्रक्रिया',
      'canada': 'कनाडा',
      'nwz': 'NWZ',
      'aus': 'ऑस्ट्रेलिया',
      'sample_documents': 'नमूना दस्तावेज़',
      'support': 'सहायता',
      'gic_guide': 'GIC गाइड',
      'appointments': 'नियुक्तियाँ',
      'fintech_services': 'फिंटेक सेवाएं',
      'rfs': 'अनुरोध फिंटेक सेवाएं',
      'afs': 'लागू की गई फिंटेक सेवाएं',
      'sop_generator': 'एआई SOP जेनरेटर',
      'course_finder': 'कोर्स खोजक',
      'upload_institute_course': 'संस्थान और कोर्स अपलोड करें',
      'inbox_configuration': 'इनबॉक्स कॉन्फ़िगरेशन',
      'sms_template': 'एसएमएस टेम्पलेट',
      'config_smtp': 'कॉन्फ़िगर SMTP',
      'email_templates': 'ईमेल टेम्पलेट्स',
      'whatsapp_temp': 'व्हाट्सएप टेम्पलेट्स',
      'campaigns': 'कैंपेन',
      'clg_agent':'कॉलेज एजेंट',
      'country':'देश',
      'intake' :'आवंटन',
      'city' : 'शहर',
      'campuses': 'कैम्पस',
      'qualification' :'योग्यता',
      'stream':'स्ट्रीम',
      'institute':'संस्थान',
      'course':'कोर्स',
      'branch': 'शाखा',
      'status' : 'स्थिति',
      'sub_status':'उप-स्थिति',
      'source':'स्रोत',
      'admision_doc_check':'प्रवेश दस्तावेज़ जाँच',
      'filing_doc_check':'फ़ाइलिंग दस्तावेज़ जाँच',
      'registration_plans':'पंजीकरण योजनाएँ',
      'expense_types':'व्यय प्रकार',
      'bank_details':'बैंक विवरण',
      'ip_add_access':'आईपी पते का उपयोग',
      'access_grant':'एक्सेस अनुमति',
      'setting':'सेटिंग',
      'apply_leaves' :'पत्ते लागू करें',
      'guides' :'मार्गदर्शिकाएँ',
      'help':'सहायता',
      'new_dmission':'नया प्रवेश',
      'all_admission':'सभी प्रवेश',
      'refund_process':'वापसी प्रक्रिया',
      'close_course_clg':'बंद कोर्स/कॉलेज',
      'reports':'रिपोर्ट्स',
      'console_report':'कंसोल रिपोर्ट',
      'count_report':'गणना रिपोर्ट',
      'filing_docs_check':'फाइलिंग दस्तावेज़ जाँच',
      'payment_approval':'भुगतान मंजूरी',
      'admissions':'प्रवेश',
      'earning_reports':'कमाई की रिपोर्ट',
      'visa_counselor':'वीजा परामर्शदाता',
      'left_counselor':'बाएँ परामर्शदाता',
      'visa_branches':'वीजा शाखाएँ',
      'left_branches':'बाईं शाखाएँ',
      'gic_request' : 'जीआईसी अनुरोध',
      'walking':'पैदल चलना',
      'call' : 'कॉल',
      'offer_latter': 'प्रस्ताव अक्षर',
      'applied':'लागू किया गया',
      'notapplied':'लागू नहीं किया गया',
      'recived':'प्राप्त',
      'notrecived':'प्राप्त नहीं हुआ',
      'reg_collection':'पंजीकरण संग्रह',
      'coll_by_reg':'पंजीकरण द्वारा संग्रह',
      'registration': 'पंजीकरण',
      'package': 'पैकेज',
      'due':'बकाया',
      'gic':'जीआईसी',
      'open':'खुला',
      'pending' : 'बकाया',
      'visa' : 'वीजा',
      'aproved' :'मंजूर',
      'refused' : 'अस्वीकृत',
      'files' :'फ़ाइलें',
      'lodge':'लॉज',
      'notlodge':'लॉज नहीं किया गया',
      'ttfee': 'टीटी शुल्क',
      'paid':'भुगतान किया',
      'notpaid' : 'भुगतान नहीं हुआ',
      'institute_fee' : 'संस्थान शुल्क',
      'earning':'कमाई',
      'target':'लक्ष्य',
      'achived' : 'प्राप्त',
    },

  };
}