

class ImageAssets {

  static const String messageIcon = 'assets/icons/message.svg';
  static const String intersetIcon = 'assets/icons/interset.svg';
  static const String formIcon = 'assets/icons/form_req.svg';
  
  static const String simIcon = 'assets/icons/sim.svg' ;
  static const  String icon= "assets/images/launcherIcon.png";
  static const String logoWhite = "assets/images/logoWhite.png";
  static const  String welcomeBg = "assets/images/welcomeBg.png";
  static const String rightArrow = "assets/images/rightArrow.png";
  static const String login = "assets/images/login.png";
  static const String home = "assets/icons/home.svg";
  static const String lead = "assets/icons/lead.svg";
  static const String graph = "assets/icons/graph.svg";
  static const String user = "assets/icons/user.svg";
  static const  String menuVector = "assets/icons/menu.svg";
  static const  String logofull = "assets/images/logo_full.png";
  static const  String messageNoti = "assets/icons/messagenoti.svg";
  static const  String appliedBg = "assets/images/bg_applied.png";
  static const  String notappliedBg = "assets/images/notApplied.png";
  static const  String notappliedIcon = "assets/icons/notrecivedicon.svg";
  static const  String recivedBg = "assets/images/received.png";
  static const  String notrecivedBg = "assets/images/notReceived.png";
  static const  String appliedIcon = "assets/icons/appliedicon.svg";
  static const  String recivedIcon = "assets/icons/recivedIcon.svg";
  static const  String filter = "assets/icons/filter.svg";
  static const  String search = "assets/icons/search.svg";
  static const  String rectangle = "assets/images/rectangle.png";
  static const  String dashbg = "assets/images/dashbg.png";
  
  static const  String vector = "assets/images/vector.png";
  static const  String gic= "assets/icons/gic.svg";
  static const  String walk= "assets/icons/walkin.svg";
  static const  String support= "assets/icons/call.svg";
  static const  String call= "assets/icons/support.svg";
  static const  String offerlatter= "assets/icons/walkin.svg";
  static const  String institutefee= "assets/icons/institute_fee.svg";
  static const  String earning= "assets/icons/earning.svg";
  static const  String more= "assets/icons/more.svg";
  static const String  visaCounselor= 'assets/icons/visa_counselor.svg';
  static const String  leftCounselor= 'assets/icons/left_counselor.svg';
  static const String  visaBranches= 'assets/icons/visa_branches.svg';
  static const String  leftBranches= 'assets/icons/left_branches.svg';
  static const String backarrow = 'assets/icons/backarrow.svg';
  static const String  canada = 'assets/icons/canada.png';
  static const String  uk = 'assets/icons/uk.png';
  static const String  australia= 'assets/icons/australia.png';
  static const String  us = 'assets/icons/us.png';
  static const String  india = 'assets/icons/india.png';
  static const String  singaore = 'assets/icons/singaore.png';
  static const  String receiptSearch = "assets/icons/receiptSearch.png";
  static const  String openTicket = "assets/icons/open-ticket.svg";
  static const  String closeticket = "assets/icons/closeticket.svg";
  static const  String todaywalk = "assets/icons/todaywalk.svg";
  static const  String monthwalk = "assets/icons/monthwalk.svg";
  static const  String answer = "assets/icons/answer.svg";
  static const  String unanswered = "assets/icons/unanswered.svg";
  static const  String userBlack = "assets/icons/user_black.svg";

  static const  String mobileBlack = "assets/icons/mobile_black.svg";
  static const  String passwordBlack = "assets/icons/password_black.svg";
  static const  String buildingBlack = "assets/icons/buildings_blak.svg";
  static const  String homeBlack = "assets/icons/home_black.svg";
  static const  String welcomeAgent = "assets/images/welcome_agent.png";
  static const  String userplaceholder = "assets/images/userplaceholder.png";
  
  static const  String totalLeads = "assets/icons/total_leads.svg";
  static const  String followUp = "assets/icons/follow_up.svg";
  static const  String totalWalkin = "assets/icons/total_walkin.svg";
  static const  String expectedWalkin = "assets/icons/expected_walkin.svg";
  static const  String todayConnection = "assets/icons/today_connection.svg";
  static const  String todaySale = "assets/icons/today_sale.svg";
  static const  String study = "assets/icons/study.svg";
  static const  String edu = "assets/icons/edu.svg";
  static const  String visitors = "assets/icons/visitors.svg";
  static const  String callBg = "assets/images/call_bg.png";
  static const  String calander = "assets/icons/calander.svg";
  static const  String followupBg = "assets/images/Followers-bro.png";
  static const  String dob = "assets/icons/dob.svg";
  static const  String gender = "assets/icons/gender.svg";
  static const  String country = "assets/icons/country.svg";
  static const  String state = "assets/icons/state.svg";
  static const  String vendor = "assets/icons/vendor.svg";
  static const  String totalfee = "assets/icons/totalfee.svg";
  static const  String deposite = "assets/icons/deposite.svg";
  static const  String amount = "assets/icons/amount.svg";
  static const  String bank = "assets/icons/bank.svg";
  static const  String accountnumber = "assets/icons/accountnumber.svg";
  static const  String ifsccode = "assets/icons/ifsccode.svg";
  static const  String micrcode = "assets/icons/micrcode.svg";
  static const  String branch = "assets/icons/branch.svg";
  static const  String bookappointment = "assets/images/bookappointment.svg";
  static const  String csv = "assets/icons/csv.svg";
  static const  String nodataIcn= "assets/icons/notdata.svg";
  static const  String searchIcn= "assets/icons/search.svg";
}